services:
  backend:
    container_name: travel-blog-api-prod
    build:
      context: .
      target: production
    ports:
      - "${PORT}:3000"
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - travel-network

    healthcheck:
      test: [
        "CMD",
        "wget",
        "--spider",
        "http://localhost:${PORT}/api/health"
      ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    container_name: travel-blog-db-prod
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    restart: unless-stopped

    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U ${DB_USERNAME}"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - travel-network


volumes:
  postgres_prod_data:


networks:
  travel-network:
    driver: bridge